-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 15:16:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema givemeacar_bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema givemeacar_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `givemeacar_bdd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `givemeacar_bdd` ;

-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`agence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agence_adresse1_idx` (`adresse_id` ASC) VISIBLE,
  CONSTRAINT `fk_agence_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `givemeacar_bdd`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `givemeacar_bdd`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `numero_compte` INT NOT NULL,
  `adresse_mail` VARCHAR(45) NOT NULL,
  `numero_telephone` INT NOT NULL,
  `adresse_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_adresse1_idx` (`adresse_id` ASC) VISIBLE,
  INDEX `fk_client_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `givemeacar_bdd`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `givemeacar_bdd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`voiture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `puissance_fiscale` VARCHAR(45) NOT NULL,
  `boite_vitesse` TINYINT NOT NULL,
  `nombre_places` INT NOT NULL,
  `carburant` VARCHAR(45) NOT NULL,
  `immatriculation` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `agence_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_voiture_agence1_idx` (`agence_id` ASC) VISIBLE,
  CONSTRAINT `fk_voiture_agence1`
    FOREIGN KEY (`agence_id`)
    REFERENCES `givemeacar_bdd`.`agence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `givemeacar_bdd`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `givemeacar_bdd`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATETIME NOT NULL,
  `fin_estimee` DATETIME NOT NULL,
  `fin_reelle` DATETIME NOT NULL,
  `voiture_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_voiture1_idx` (`voiture_id` ASC) VISIBLE,
  INDEX `fk_location_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_voiture1`
    FOREIGN KEY (`voiture_id`)
    REFERENCES `givemeacar_bdd`.`voiture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `givemeacar_bdd`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
